### PR TITLE
std::pow(-2,N) unit tests with DualNumbers

### PR DESCRIPTION
**Pull request by roystgnr**
These pass for me; maybe if they break in CI then we can figure out why the same operations are failing for @dschwen 

Refs https://github.com/roystgnr/MetaPhysicL/issues/82

### CODE REVIEW

**Comment by dschwen** [comment]
I don't see a `libMesh::enableFPE(true);` here. Are you sure FPEs are handled?

**Comment by dschwen** [comment]
Just to clarify, the results are fine, but the fact that an FPE is raised in the process is already concerning enough. This will break MOOSE simulations in dbg mode (where FPEs are enabled by default).

**Comment by roystgnr** [comment]
No, I didn't have FPEs enabled.  And there's the problem.  MetaPhysicL::if_else() is non-short-circuiting (less efficient for scalars, but necessary to make it work at all for vectors), so we take log(-2) before we decide we can throw it away, so the FPE gets triggered even though we never read the resulting NaN.

We might be able to just add more explicit non-dualnumber-exponent overloads here.  Right now, the "supertype" metafunction has no way to detect that for this particular function argument we really can safely treat int as int without upconverting it to a DualNumber, so we end up doing a runtime check that the exponent has no derivatives.

In the meantime - I don't suppose you know your exponents at compile time?  `libMesh::do_pow<some_small_int>` is still going to be more efficient than whatever fix we can find for the only-known-at-runtime case.

**Comment by dschwen** [comment]
Yeah, `libMesh::do_pow<some_small_int>` is the same as `libMesh::Utility::pow<int>`>? We also have runtime integer powers routine in MOOSE that we could use if we don't know the integer powers at compile time.

**Comment by roystgnr** [comment]
Apologies, yes; `do_pow` is an implementation internal.

**Comment by dschwen** [comment]
> MetaPhysicL::if_else() is non-short-circuiting (less efficient for scalars, but necessary to make it work at all for vectors)

I see...

```
MetaPhysicL::if_else(b.derivatives(), b.derivatives() * std::log(a.value()) * a.value(), b.derivatives())))
```

couldn't you make it short circuit by passing in lambdas instead of pre evaluated arguments?

**Comment by dschwen** [comment]
Maybe expression templates could help here. https://www.modernescpp.com/index.php/expression-templates

But that seems like a big design change.

**Comment by roystgnr** [comment]
I've actually got a fix for this case now, almost ready for a PR.

When I turned on FP exceptions by default to make sure there was nothing else like this rooting around in the library, I applied a couple obvious fixes to broken tests ... and then I ran into this one, from your test:

```
DualNumber<float, float> big = 800.0;
  if (!std::isinf(std::exp(big)))
```

We never make it to `isinf`.  `std::exp(big)` has a value of `big.value()` (infinity, for float) and a derivative of `big.derivatives() * big.value()` (i.e. zero times infinity, which then throws a floating point exception).

This was your unit test - can I just "cheat" here by setting derivatives to 1, so we get finite*infinity instead?

**Comment by dschwen** [comment]
> This was your unit test - can I just "cheat" here by setting derivatives to 1, so we get finite*infinity instead?

Haha. Sweet irony. Yeah, of course. That seems like the right fix.

**Comment by roystgnr** [comment]
CI seems to be happy with it, at least.  Though at some point I should probably set up another PR with a deliberately introduced FP exception just to make sure the CI tests fail there, that those builds are correctly detecting fenv.h and all.

**Pull request merged**
