### PR TITLE
Add assignment operators for StandardType

### PR DESCRIPTION
**Pull request by lindsayad**

### CODE REVIEW

**Comment by lindsayad** [comment]
@roystgnr we get the `std::make_unique` errors here on min compilers

**Comment by roystgnr** [comment]
I'm kind of baffled.  We're using the exact same `ACSM_CXX_COMPILER_STANDARD([2011], [2017])` in configure.ac here that we are in libMesh configure.ac ... Oh, but wait.  We're failing the TIMPI build.  And the TIMPI build doesn't bother getting picky about compiler standards because in practice it's never needed to: libMesh sees optional C++14 support in our Min compilers and passes the necessary flags on to TIMPI, and the CI on TIMPI itself is using new enough compilers that the C++14 support is there by default.

Well, it's time to start mandating C++17 anyway.  I'll add that macro to TIMPI configure.ac tomorrow, only mandating C++14 for the moment, and then we can experiment with turning up the requirements and see what our new Min versions of clang and gcc are going to need to be.

**Comment by roystgnr** [comment]
Okay, that's fun.  g++ 4.8.5 is a "C++1y" compiler but not a C++14 compiler.

**Comment by lindsayad** [comment]
I'm all for just saying screw it, our min is C++17 😄

**Comment by roystgnr** [comment]
Doing some more research: not only is gcc 8 the minimum default on RHEL 8 and derivatives, but RHEL 7 users (and derivatives?  I seem to see devtoolset in a CentOS 7 repo) can get the Developer Tool Set to easily install a prebuilt gcc up to version 9.1 ... and even RHEL 6 users can get a DTS release supporting gcc 8.2.  Yes, that's RHEL 6, initial release 2010, non-Extended support ended 2020.

I'll bet some other OS distributors are behind Red Hat here, but they can't be *that* far behind.

Time to dump gcc 4.8.

**Comment by roystgnr** [comment]
I'm going to try restarting from scratch in a new branch/PR for this.  Even if I rebase to fix the valgrind issues and kick it to get tests with newer compilers (maybe twice? I updated the gcc test but this is going to need a newer clang too...), it's still using the old repeatedly-commit-and-free paradigm, and we might as well update it to use TIMPI::SemiPermanent instead.

**Comment by lindsayad** [comment]
Sounds good. Closing in favor of #6

**Pull request closed without merging**
