### PR TITLE
Make some types potentially trivially constructable

### PR DESCRIPTION
**Pull request by lindsayad**
- DualNumber
- SemiDynamicSparseNumberArray

### CODE REVIEW

**Comment by lindsayad** [comment]
I don't think we actually ever make any attempt to define `METAPHYSICL_USE_STD_MOVE` so probably in the past we've never allowed move operations. I've removed use of that macro but can restore it if requested

**Comment by lindsayad** [comment]
Oh min clang failure ... that should be fun

**Comment by roystgnr** [comment]
>I don't think we actually ever make any attempt to define METAPHYSICL_USE_STD_MOVE

Take a look at metaphysicl_common.h

>Oh min clang failure ...

Precisely.

**Comment by lindsayad** [comment]
Haha, precisely indeed!
```
#if __cplusplus >= 201103L

// But if we have e.g. clang 9, then we've seen SIGFPE triggered when
// using optimizations on rvalue references, in code that raises no
// warnings and no valgrind errors from -O0, or from any configuration
// of five other compilers ... so we're just going to make things as
// easy on clang as possible, and if we want more optimized code we're
// going to want a better compiler.
//
// I don't have clang++-10 handy to check with, so I'm not going to
// trust it either.
#ifndef __clang__
#define METAPHYSICL_USE_STD_MOVE 1
#else
#  if __clang_major__ > 10
#  define METAPHYSICL_USE_STD_MOVE 1
#  else
#  undef METAPHYSICL_USE_STD_MOVE
#  endif
```

**Comment by roystgnr** [comment]
You know, maybe we don't just need to weaken those assertions in `Point`, maybe we need to get rid of them entirely, but add `Packing<Point<T>>` specializations that take effect whenever `T` needs to be packed?  We *could* create a `StandardType` for a `T` that incorporates N=300 semidynamic arrays, but in that case it would usually be much more efficient to just take the hit and only pack the used entries of the array.

**Comment by lindsayad** [comment]
We do already have `StandardType<SemiDynamicSparseNumberArray>` in `parallel_semidynamicsparsenumberarray.h` but yea I see what you're saying. We could replace that with a `Packing`. I forget whether we have an `enable_if` for `StandardType` ... it might make sense to use `StandardType` for sufficiently small `N` and `Packing` for larger `N`? Might be more trouble than it's worth to try and do that switching though

**Comment by roystgnr** [comment]
Thinking about efficiency: we would love to use `StandardType` for collections of arrays with small `N` and/or `_dynamic_n` near `N`, we'd love to use `Packing` for collections of arrays where most of them have `_dynamic_n` much less than `N`, and we don't really care what we use for a single array where communication latency won't change much either way and bandwidth isn't important.

But this is nasty...

Thinking about correctness: if we take away `StandardType` for any numeric array we use ... does my recent `OpFunction` stuff, that parts of `MOOSE` now depend on, work with variable-size data types?  I'm ashamed to say I'm not sure I tested that with a true `DynamicSparseNumberArray` backend in `ADReal`, vs `NumberArray` and `SemiDynamicNumberArray`... and I'm not sure off the top of my head if it's even possible to make MPI reductions work with variable-size types (rather than just variable-size containers of fixed-size types).

**Comment by lindsayad** [comment]
> does my recent `OpFunction` stuff, that parts of `MOOSE` now depend on, work with variable-size data types? I'm ashamed to say I'm not sure I tested that with a true `DynamicSparseNumberArray` backend in `ADReal`, vs `NumberArray` and `SemiDynamicNumberArray`

I have a vague memory that it does not work, from when I was working on the memory pool this summer, but I can't say with 100% certainty.

**Comment by roystgnr** [comment]
Oh, that's horrible.  I was kind of hoping that we could someday get true DSNA fast enough to at least be workable as a "doesn't care how much physics you throw at it" default, with instructions on how to switch to fixed-N SDSNA or NA for users who want to optimize.  But I was not expecting that this would also require figuring out how to reimplement `MPI_Reduce` and `MPI_Allreduce` from scratch.  (easy enough to make something that works, but don't they have network-topology-aware algorithms to make it scale efficiently?)

**Comment by lindsayad** [comment]
Per last testing DSNA is within talking, maybe spitting, distance of SDSNA and so could definitely in line for consideration as a possible AD type in applications per the results in https://github.com/libMesh/MetaPhysicL/pull/29. I remember that I couldn't use `navier_stokes` for testing because I couldn't compile... but now that I think about it, that would probably be related to my parallel code in `navier_stokes` and not the parallel reduce operations you did for `thermal_hydraulics`. I don't actually know where your parallel reduce code is, but if it's in the framework or higher it would have impacted `tensor_mechanics` compiling which was successful; and if it was in `thermal_hydraulics` well we don't compile that with `navier_stokes` so that couldn't have been the problem.

**Comment by lindsayad** [comment]
No longer need

**Pull request closed without merging**
