### PR TITLE
Make member protected

### PR DESCRIPTION
**Pull request by dschwen**
There was one assertion left that I think was overzealous.

Closes roystgnr/MetaPhysicl#76 :-D

### CODE REVIEW

**Comment by lindsayad** [comment]
> There was one assertion left that I think was overzealous.

that's embarrassing

**Review by lindsayad — APPROVED** [review]

**Comment by lindsayad** [comment]
@dschwen could we actually try changing things like the definition of `end()` to avoid the extra op? Similar to what you have in your MOOSE PR? I remember that in past profiles, `end()` itself has actually shown up due to the sheer number of times it's called. Reducing ops could be important

**Comment by roystgnr** [comment]
Looks good.  I guess there was little hope of catching the N-1 case in testing...

**Comment by dschwen** [comment]
> @dschwen could we actually try changing things like the definition of `end()` to avoid the extra op? 

Yeah, I'll make another quick PR for that.

**Pull request merged**
